"""
app/pages/signals.py
======================
Signal history page — filterable table of all past signals.
"""

import os
import json
import pandas as pd
import streamlit as st
import plotly.express as px

from config.settings import COINS, COIN_DISPLAY, SIGNAL_LOG


def _load_log() -> pd.DataFrame:
    if not os.path.exists(SIGNAL_LOG):
        return pd.DataFrame()
    try:
        with open(SIGNAL_LOG) as f:
            data = json.load(f)
        return pd.DataFrame(data)
    except Exception:
        return pd.DataFrame()


def render():
    st.title("📋 Signal History")
    st.caption("Complete log of every signal generated by the model.")

    df = _load_log()

    if df.empty:
        st.info(
            "No signal history yet.\n\n"
            "Signals are logged automatically every hour when `main.py` is running."
        )
        return

    # ── Filters ───────────────────────────────────────────────────────────────
    st.subheader("Filters")
    fc1, fc2, fc3 = st.columns(3)

    with fc1:
        coin_filter = st.multiselect(
            "Coin", list(COINS.values()),
            format_func=lambda c: COIN_DISPLAY.get(c, c),
        )
    with fc2:
        sig_filter = st.multiselect("Signal", ["BUY", "SELL", "HOLD"])
    with fc3:
        min_conf = st.slider("Min confidence", 0.0, 1.0, 0.0, 0.05,
                             format="%.0f%%")

    filtered = df.copy()
    if coin_filter and "coin" in filtered.columns:
        filtered = filtered[filtered["coin"].isin(coin_filter)]
    if sig_filter and "signal" in filtered.columns:
        filtered = filtered[filtered["signal"].isin(sig_filter)]
    if "confidence" in filtered.columns:
        filtered = filtered[filtered["confidence"] >= min_conf]

    # ── Summary metrics ───────────────────────────────────────────────────────
    st.markdown("---")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total signals", len(filtered))

    if "signal" in filtered.columns and len(filtered):
        buy_pct  = (filtered["signal"] == "BUY").mean()  * 100
        sell_pct = (filtered["signal"] == "SELL").mean() * 100
        m2.metric("BUY",  f"{buy_pct:.1f}%")
        m3.metric("SELL", f"{sell_pct:.1f}%")

    if "confidence" in filtered.columns and len(filtered):
        m4.metric("Avg confidence", f"{filtered['confidence'].mean():.1%}")

    # ── Charts ────────────────────────────────────────────────────────────────
    if len(filtered) > 5 and "signal" in filtered.columns:
        col_a, col_b = st.columns(2)

        with col_a:
            counts = filtered["signal"].value_counts()
            fig = px.pie(
                values=counts.values, names=counts.index,
                color=counts.index,
                color_discrete_map={
                    "BUY": "#16a34a", "SELL": "#dc2626", "HOLD": "#d97706"
                },
                hole=0.4, title="Signal distribution",
            )
            fig.update_layout(height=280, margin=dict(t=40, b=0))
            st.plotly_chart(fig, use_container_width=True)

        with col_b:
            if "coin" in filtered.columns:
                coin_counts = filtered["coin"].value_counts()
                fig2 = px.bar(
                    x=coin_counts.index, y=coin_counts.values,
                    labels={"x": "Coin", "y": "Count"},
                    title="Signals per coin",
                    color=coin_counts.index,
                )
                fig2.update_layout(height=280, margin=dict(t=40, b=0),
                                   showlegend=False)
                st.plotly_chart(fig2, use_container_width=True)

    # ── Table ─────────────────────────────────────────────────────────────────
    st.markdown("---")
    st.subheader(f"Signal log ({len(filtered)} rows)")

    display_cols = [c for c in [
        "timestamp", "coin", "signal", "confidence",
        "price", "target_price", "stop_loss_price", "risk_reward", "rsi",
    ] if c in filtered.columns]

    if display_cols:
        show = filtered[display_cols].copy()
        if "timestamp" in show.columns:
            show = show.sort_values("timestamp", ascending=False)
        if "confidence" in show.columns:
            show["confidence"] = show["confidence"].apply(lambda x: f"{x:.0%}")
        if "coin" in show.columns:
            show["coin"] = show["coin"].apply(lambda c: COIN_DISPLAY.get(c, c))

        st.dataframe(show.head(200), use_container_width=True, hide_index=True)

    # ── Download ──────────────────────────────────────────────────────────────
    if len(filtered) > 0:
        csv = filtered.to_csv(index=False)
        st.download_button(
            "⬇ Download CSV",
            data=csv,
            file_name="algobot_signals.csv",
            mime="text/csv",
        )